# Site settings
title: 尹锋以为
email:  ingf.ivan@gmail.com
description: > # 
  Less is More
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ingf.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  ingf

# Build settings
markdown: kramdown

paginate: 50

author: inf

gems: [jekyll-paginate]
